#!/usr/bin/env python3
"""
File:     tools/dotnet-ci/generate_projects.py
Created:  2026-06-12
Purpose:  Generate plain .NET SDK projects (*.gen.csproj) from the Unity
          assembly definitions (*.asmdef) under src/, plus a solution file, so
          the entire tree compiles and every NUnit suite runs under
          `dotnet test` on Linux CI — without Unity.

          NON-CERTIFYING GATE. The determinism certification platform remains
          the pinned Windows 11 / Unity 2022.3.62f1 / Mono tuple
          (docs/tracking/certification-platform.md). This gate exists to catch
          the never-compiled / dead-test-suite defect class (PassMechanicsTests
          CS1022, First Touch ERR-004, Decision Tree AR-2 H-1) at commit time.

          Design rules:
          - The .asmdef files are the single source of truth: csprojs are
            regenerated on every run (locally and in CI) and are gitignored.
            Nothing here is hand-maintained per assembly.
          - AssemblyName == asmdef "name" so InternalsVisibleTo attributes in
            the checked-in AssemblyInfo.cs files resolve unchanged.
          - LangVersion is pinned to 9.0 (Unity 2022.3 C# level) so code that
            passes this gate cannot silently adopt language features the Unity
            compiler would reject.
          - DEVELOPMENT_BUILD is defined so the FR-CS-031-gated diagnostic
            emits (#if UNITY_EDITOR || DEVELOPMENT_BUILD) compile and run,
            keeping the LogAssert.Expect() assertions meaningful.
          - Test projects (asmdef name ends in ".Tests") get NUnit + the
            NUnit3 adapter + the UnityShim.TestTools log contract (assembly-
            level LogAssertVerify action attribute, linked in).

Usage:    python3 tools/dotnet-ci/generate_projects.py
          dotnet test tools/dotnet-ci/TacticalDirector.gen.sln
"""

import json
import sys
import uuid
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SRC = REPO_ROOT / "src"
TOOLS = REPO_ROOT / "tools" / "dotnet-ci"
SLN_PATH = TOOLS / "TacticalDirector.gen.sln"

# Unity-side references that have no .NET-side project; NUnit comes from NuGet.
UNITY_ONLY_REFS = {"UnityEngine.TestRunner", "UnityEditor.TestRunner"}

NUNIT_VERSION = "3.14.0"
ADAPTER_VERSION = "4.6.0"
TEST_SDK_VERSION = "17.11.1"

# Stable namespace for deterministic project GUIDs (arbitrary but fixed).
GUID_NS = uuid.UUID("7d4cf0d4-2e3a-4f4b-9a64-0d6d54f7a2c1")


def project_guid(name: str) -> str:
    return "{" + str(uuid.uuid5(GUID_NS, name)).upper() + "}"


def load_asmdefs():
    """Return {asmdef_name: {dir, stem, data}} for every asmdef under src/."""
    asmdefs = {}
    for path in sorted(SRC.rglob("*.asmdef")):
        data = json.loads(path.read_text(encoding="utf-8"))
        name = data["name"]
        if name in asmdefs:
            sys.exit(f"ERROR: duplicate asmdef name {name!r} "
                     f"({path} vs {asmdefs[name]['dir']})")
        asmdefs[name] = {"dir": path.parent, "stem": path.stem, "data": data}
    return asmdefs


def nested_asmdef_dirs(own_dir: Path, all_dirs):
    """Directories of OTHER asmdefs nested under own_dir (Unity scoping rule:
    each .cs file belongs to the nearest enclosing asmdef)."""
    out = []
    for d in all_dirs:
        if d != own_dir and own_dir in d.parents:
            out.append(d)
    return out


def gen_csproj(name, info, asmdefs):
    own_dir = info["dir"]
    data = info["data"]
    is_test = name.endswith(".Tests")
    all_dirs = [v["dir"] for v in asmdefs.values()]

    lines = []
    lines.append("<!-- GENERATED by tools/dotnet-ci/generate_projects.py from "
                 f"{info['stem']}.asmdef — do not edit, do not commit. -->")
    lines.append('<Project Sdk="Microsoft.NET.Sdk">')
    lines.append("  <PropertyGroup>")
    # Production assemblies compile against netstandard2.1 — Unity 2022.3's actual
    # BCL surface — so .NET-8-only API shape changes (e.g. MemoryMarshal.Write
    # ref->in) cannot mask or manufacture compile errors relative to the engine.
    # Test assemblies need net8.0 for the NUnit3 adapter / Microsoft.NET.Test.Sdk;
    # netstandard2.1 references are binary-compatible at runtime.
    tfm = "net8.0" if is_test else "netstandard2.1"
    lines.append(f"    <TargetFramework>{tfm}</TargetFramework>")
    lines.append("    <LangVersion>9.0</LangVersion>")
    lines.append(f"    <AssemblyName>{name}</AssemblyName>")
    root_ns = data.get("rootNamespace") or name
    lines.append(f"    <RootNamespace>{root_ns}</RootNamespace>")
    lines.append("    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>")
    lines.append("    <Deterministic>true</Deterministic>")
    lines.append("    <Nullable>disable</Nullable>")
    lines.append("    <DefineConstants>$(DefineConstants);DEVELOPMENT_BUILD</DefineConstants>")
    lines.append("    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>")
    if is_test:
        lines.append("    <IsPackable>false</IsPackable>")
    lines.append("  </PropertyGroup>")

    # Compile items: everything under this asmdef's dir except subtrees owned
    # by nested asmdefs and build output dirs.
    lines.append("  <ItemGroup>")
    lines.append('    <Compile Include="**/*.cs" Exclude="obj/**;bin/**" />')
    for nested in nested_asmdef_dirs(own_dir, all_dirs):
        rel = nested.relative_to(own_dir).as_posix()
        lines.append(f'    <Compile Remove="{rel}/**" />')
    if is_test:
        link = (TOOLS / "LogAssertVerifyAssemblyInfo.cs").relative_to(REPO_ROOT)
        rel = Path("../" * len(own_dir.relative_to(REPO_ROOT).parts)) / link
        lines.append(f'    <Compile Include="{rel.as_posix()}" '
                     'Link="LogAssertVerifyAssemblyInfo.cs" />')
    lines.append("  </ItemGroup>")

    # References.
    lines.append("  <ItemGroup>")
    depth = len(own_dir.relative_to(REPO_ROOT).parts)
    to_root = "../" * depth
    lines.append(f'    <ProjectReference Include="{to_root}tools/dotnet-ci/UnityShim/UnityShim.csproj" />')
    # Unity 2022.3 bundles System.Runtime.CompilerServices.Unsafe.dll; outside the
    # netstandard2.1 box it is a NuGet package. Mirrors the engine environment.
    lines.append('    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />')
    for ref in data.get("references", []):
        if ref in UNITY_ONLY_REFS:
            continue
        if ref not in asmdefs:
            sys.exit(f"ERROR: {name} references unknown assembly {ref!r}")
        rdir = asmdefs[ref]["dir"]
        rel = Path("../" * depth) / rdir.relative_to(REPO_ROOT) / f"{asmdefs[ref]['stem']}.gen.csproj"
        lines.append(f'    <ProjectReference Include="{rel.as_posix()}" />')
    if is_test:
        lines.append(f'    <ProjectReference Include="{to_root}tools/dotnet-ci/UnityShim.TestTools/UnityShim.TestTools.csproj" />')
        lines.append(f'    <PackageReference Include="NUnit" Version="{NUNIT_VERSION}" />')
        lines.append(f'    <PackageReference Include="NUnit3TestAdapter" Version="{ADAPTER_VERSION}" />')
        lines.append(f'    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="{TEST_SDK_VERSION}" />')
    lines.append("  </ItemGroup>")
    lines.append("</Project>")

    out = own_dir / f"{info['stem']}.gen.csproj"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def gen_solution(projects):
    """Hand-rolled .sln — format is stable and this avoids `dotnet sln` churn."""
    csproj_type = "{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}"  # C# project type GUID
    header = [
        "Microsoft Visual Studio Solution File, Format Version 12.00",
        "# Generated by tools/dotnet-ci/generate_projects.py — do not edit, do not commit.",
    ]
    body, globals_ = [], []
    for name, path in projects:
        guid = project_guid(name)
        rel = path.relative_to(TOOLS.parent.parent) if path.is_absolute() else path
        rel_win = str(rel).replace("/", "\\")
        body.append(f'Project("{csproj_type}") = "{name}", "..\\..\\{rel_win}", "{guid}"')
        body.append("EndProject")
        for cfg in ("Debug", "Release"):
            globals_.append(f"\t\t{guid}.{cfg}|Any CPU.ActiveCfg = {cfg}|Any CPU")
            globals_.append(f"\t\t{guid}.{cfg}|Any CPU.Build.0 = {cfg}|Any CPU")
    sln = header + body + [
        "Global",
        "\tGlobalSection(SolutionConfigurationPlatforms) = preSolution",
        "\t\tDebug|Any CPU = Debug|Any CPU",
        "\t\tRelease|Any CPU = Release|Any CPU",
        "\tEndGlobalSection",
        "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution",
        *globals_,
        "\tEndGlobalSection",
        "EndGlobal",
    ]
    SLN_PATH.write_text("\n".join(sln) + "\n", encoding="utf-8")


def main():
    asmdefs = load_asmdefs()
    projects = [
        ("UnityShim", TOOLS / "UnityShim" / "UnityShim.csproj"),
        ("UnityShim.TestTools", TOOLS / "UnityShim.TestTools" / "UnityShim.TestTools.csproj"),
    ]
    n_test = 0
    for name, info in asmdefs.items():
        path = gen_csproj(name, info, asmdefs)
        projects.append((name, path))
        if name.endswith(".Tests"):
            n_test += 1
    gen_solution([(n, p.relative_to(REPO_ROOT)) for n, p in projects])
    print(f"Generated {len(asmdefs)} csproj ({n_test} test projects) + "
          f"{SLN_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
